### ISSUE TITLE
Tensorflow 1.15.2 incompatiability with python 3.8

### ISSUE THREAD

**Issue by andret6** [appeler/ethnicolr#29] opened 2020-06-24 19:21 UTC
Big fan of this, use it all the time for criminal legal system data in particular, thank you for making it.  This seems similar to previous tensorflow issues that are closed, but am flagging in case others had this issue with trying to run from 3.8.

Python 3.8 is not compatible with TensorFlow 1.15.2, tensorflow documentation here: https://www.tensorflow.org/install/pip

Pip install with 3.8 will install ethnicolr but will install Tensorflow 2.2, and return the following error message with importing ethnicolr:

```
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:
...
Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

Easy work around by running on 3.7 for now.

**Comment by andret6** [comment] 2020-07-20 18:02
Also heads up, may need to use a previous version of Keras as well, 2.1.6 is working for me, 2.4.0 was not compatible with tensorflow 1.15.2

**Comment by AnanthVivekanand** [comment] 2020-07-28 16:59
This is caused by commit 79901af. That commit removed the pins on the Tensorflow and Keras versions for support with Python 3.8.

**Comment by sbuss** [comment] 2020-08-09 21:51
Sorry for creating the bug in #27. When I made that change all of the tests passed, so I assumed it was OK, and @soodoku didn't find any issues either. It seems the test suite in the package doesn't have enough coverage.

It looks like the model file format may have undergone a breaking change in Tensorflow 1.x -> 2.x., or at Keras 2.4 It might only be fixable by rebuilding the model, but I don't know enough about tensorflow or keras to say for certain.

I think 79901afacf71e5434067d056138161dcef02677b should be reverted for now and let it be a known limitation that ethnicolr doesn't support python 3.8.

**Comment by AnanthVivekanand** [comment] 2020-08-09 22:52
Ok great, I made a PR that reverts Python 3.8 compatibility and also adds a note in the README to state that only Python 3.7 and lower should be used.

**Comment by soodoku** [comment] 2021-02-15 19:24
We will move to tensorflow 2.0 soon. Will post here to close this thread.

**Comment by soodoku** [comment] 2021-06-16 20:29
we have moved to tf 2.0+. you will see a new release soon.

**Comment by suriyan** [comment] 2021-06-23 02:57
Please checkout [v0.6.1](https://github.com/appeler/ethnicolr/releases/tag/v0.6.1) for Python 3.8 support (now switch to use TensorFlow 2.5.0)

**Closed by suriyan** 2021-06-23 02:57 UTC
Labels: enhancement
